#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sat May 01 18:57:54 EDT 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 394c86f2dad24bd5a7a8cf81ae1211ec --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot mips_tb_b_behav xil_defaultlib.mips_tb_b -log elaborate.log"
xelab -wto 394c86f2dad24bd5a7a8cf81ae1211ec --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot mips_tb_b_behav xil_defaultlib.mips_tb_b -log elaborate.log

